### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by asosnovsky** [unindented/grunt-electron-windows-installer#2]
So I have been trying out this for the first time.
I attempted both your explanations in the tutorial, but I keep getting the same error.
![de34897273](https://cloud.githubusercontent.com/assets/7451445/9130439/a99fe0de-3cb0-11e5-9717-41a22e8d18a1.png)

I tried upgrading NuGet, by copy pasting the new version on top of the one in `myApp\node_modules\grunt-electron-windows-installer\vendor\nuget\`, but no luck there.

EDIT:
Just thought of something, I am running win-10, any chance that could cause this?
I will test this tomorrow morning.

**Comment by unindented** [comment]
I don't think it's Win10. According to that error message, the `<metadata>` block that NuGet is expecting is missing two properties: `description` and `authors`.

`description` gets populated by default with the `description` field of your `package.json`. If you don't have one, you can add it, or alternatively pass that manually to the Grunt task.

`authors` gets populated by default with the `author` field of your `package.json`. Again, if you don't have one, you can add it, or pass it to the Grunt task.

Let me know if that worked for you.

**Comment by unindented** [comment]
I've tried to explain things better with this commit: https://github.com/unindented/grunt-electron-windows-installer/commit/f0499ca6687058175a1179c7bfc5ee4c89165764
